# Generated by Django 4.1.4 on 2023-01-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('condition', models.CharField(choices=[('monotributista', 'monotributista'), ('responsable inscripto', 'responsable inscripto')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
