# Generated by Django 4.1.4 on 2023-02-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_userprofile_users_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='users',
        ),
    ]
