# Generated by Django 4.1.4 on 2023-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0002_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='categories', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
