# Generated by Django 4.1.4 on 2023-01-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.IntegerField()),
                ('price', models.FloatField()),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
