# Generated by Django 4.1.4 on 2023-01-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_product_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(choices=[('offroad', 'Offroad'), ('street', 'Street'), ('scooter', 'Scooter')], max_length=50),
        ),
    ]
