# Generated by Django 4.1.4 on 2023-01-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(choices=[('Offroad', 'Offroad'), ('Street', 'Street'), ('Scooter', 'Scooter')], max_length=50),
        ),
    ]
