# Generated by Django 4.1.4 on 2023-01-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Imagen'),
        ),
    ]
